### ISSUE TITLE
Feature: Implementar modo debug ou similiar

### ISSUE THREAD

**Issue by exodojaffar** [henriqueclaranhan/flappy-bird-game#5]
## Modo Debug
Muito util para testar funcionalidades e monitorar valores, recomendo e peço que tenha.

## Por que?
Queria testar o jogo, mas como não consigo mudar o codigo diretamente no navegador, não é possivel de debug sem baixar o codigo e rodar de forma individual.

**Comment by henriqueclaranhan** [comment]
Vou pensar sobre isso.
